### ISSUE TITLE
About the design of stem

### ISSUE THREAD

**Issue by Lelucermaire111** [liruiw/HPT#10]
Hi! Thanks for your great and interesting work! I have a question about the design of stem: why you adopt the cross-attention to get the proprioception tokens and vision tokens? Does the performance will degrade if I use the features as queries and use the self-attention? Looking forward to your reply!

**Comment by liruiw** [comment]
Thanks for the question. The motivation for using cross-attention is that we want to use a small fixed number of tokens across different embodiments. E.g. 10 steps of 7-dof robot and 1 step of 23-dof humanoid should be mapped to the same number of tokens such that it's easier for the trunk to learn patterns on the representations.

**Comment by Lelucermaire111** [comment]
Thanks for your reply! I am not very familiar with the robotics problem, so does it mean that the stem maps the sequence of features with different lengths into 16 fixed tokens? In other words, for different tasks, the sequence, dimension and image resolution are all different, so we need to map them into fixed tokens. I would appreciate it again if you could reply!
