### ISSUE TITLE
Issue about the ation dimension of bridge domain

### ISSUE THREAD

**Issue by KaiLiu18** [liruiw/HPT#11]
Hello.
Thanks for your work.
When I attempt to apply a policy to bridge dataset using a pre-trained model (hpt-base), I encounter an issue where the action dimension for the bridge domain is 6, whereas it should ideally be 7 (comprising x, y, z, roll, pitch, yaw, and gripper). So I wonder what's the meaning of the output action or if I might have overlooked something in the process?

**Comment by liruiw** [comment]
I noticed this probelm earlier as well. I think the gripper dimension is not included in my data processing so  it's dimension 6.
