### ISSUE TITLE
Issue about language instruction

### ISSUE THREAD

**Issue by yyysk** [liruiw/HPT#12]
Thanks for your great job. I have a question about generating language data.
In file "HPT/env/mujoco/metaworld/rollout_runner.py", line 171 & line 266, 
`language_instruction = [task for (task, _, _, _, lang) in ALL_TASK_CONFIG if task == env][0]`,
I wonder why use `task` as language_instruction rather than `lang`.

**Comment by liruiw** [comment]
I believe that the language is just my manual annotations. In HPT, we really didn't explore that much on the language conditioning in policies.
