### ISSUE TITLE
Issue about running HPT on the Simpler Benchmark

### ISSUE THREAD

**Issue by KaiLiu18** [liruiw/HPT#15]
Thank you for your commendable work! Recently, I have been attempting to finetune HPT on the RT1-X supervised datasets based on your paper. However, the finetuned model doesn't played as well as predicted. Could you please provide more detailed information about finetuning HPT on the RT1-X supervised datasets, including how to correctly generate and prepare the training data?

**Comment by liruiw** [comment]
Thanks for asking this. I only tried HPT on the tasks with the Google Robots in the Simpler Benchmark. The generated data has proprioception inputs (See this [PR](https://github.com/simpler-env/SimplerEnv/pull/3)).
