### ISSUE TITLE
Issue about the code of data processing in the pre-training stage

### ISSUE THREAD

**Issue by CZtheHusky** [liruiw/HPT#16]
Hello!

Thank you for your insightful work—it’s incredibly informative and inspiring. I noticed that the dimensions of the proprioception inputs in several datasets differ from those in Octo and OpenVLA. Do you have any plans to release the code for data processing? I'm particularly interested in exploring the shared latent space, but without the appropriate training inputs, it’s challenging to delve deeper into this topic.

**Comment by liruiw** [comment]
The preprocessing steps for pre-training still needs some cleanup. I think the information in the proprioception inputs are all contained and filtered based on the keys of the observation dictionary, so different works might have chosen different inputs. The relevant part of code should be as follows

```
def select_state(observation: dict, verbose: bool = False) -> np.ndarray:
    """
    Select a state representation for the dataset.
    If there is already a state representation, just use it.
    If there exist end effector and joint positions, add both.
    otherwise add whatever available.
    """
    if "state" in observation:
        state = observation["state"].numpy()
        if verbose:
            print("selected state key:", "state")
        return state

    joint_and_ee = []
    for key in observation.keys():
        if "joint" in key or "state" in key:
            joint = observation[key].numpy()
            if verbose:
                print("selected state key:", key)
            joint_and_ee.append(joint)

    for key in observation.keys():
        if "ee" in key or "pose" in key or "effector" in key or "xyz" in key:
            ee_state = observation[key].numpy()
            if verbose:
                print("selected state key:", key)
            joint_and_ee.append(ee_state)

    # return joint and ee
    if len(joint_and_ee) > 0:
        return np.concatenate(joint_and_ee)

    # no propriceptive info is available
    return None
```
