### ISSUE TITLE
Questions about some technical details

### ISSUE THREAD

**Issue by zengweishuai** [liruiw/HPT#17]
Hi wang @liruiw , excited to see your work and code!

I've got some questions about the paper and I am not sure if my understanding is correct so I'd love to inquire you about some tiny places in your paper and hope to receive your reply~

The question is that, assuming that we've determined one specific embodiment to execute and we've selected the corresponding head and stem, what is the length of the state and action sequences? 

I've noticed that in Appendix, you mention we pick a fixed action horizon (length 8) and observation horizon (length 4) for each embodiment. Does it mean that the state sequence to the stem is (proprioception sequences of length 4 + images sequence of length 4) and the action in the end is a sequence of length 8? 

Then during training, the state input here should be (p_0, p_1, p_2, p_3, i_0, i_1, i_2, i_3) and the action output is (a_4,a_5,a_6,a_7,a_8,a_9,a_10,a_11)? 

I find myself bewildered about this part of the paper. Expect your reply!!!

**Comment by liruiw** [comment]
This is correct. During pre-training, the observation history is of length 4 and the action "chunk" length is 8. There are two caveats: (1) there could be multiple instances in the observation space. For example, there can be multiple views of vision input. (2) During transfer learning, we can always fine-tune the stem and the head to use a particular history length or action horizon. It does not have to be the same as in pre-training.
