### ISSUE TITLE
Clarification Needed on State Dimensions for Custom Dataset

### ISSUE THREAD

**Issue by 2814894078** [liruiw/HPT#18]
Hello,

Thank you for your work on this project. I have a question regarding creating a custom dataset. When setting up the state data, how many dimensions should it have, and what should each dimension represent? I understand that action typically includes x, y, z, roll, pitch, yaw, but I’m unsure about the specific components required for state. Could you clarify the expected format and content for the state field?

Thank you for your assistance!

**Comment by liruiw** [comment]
The definition of the states and their dimensions depend on the specific tasks and datasets. There is no hardcoded format and content for it.
