### ISSUE TITLE
are you going to make the training code and data available?

### ISSUE THREAD

**Issue by zwbx** [liruiw/HPT#2]
Thank you for the excellent work! I was wondering if the original training code and data will be open-sourced in the future.

**Comment by liruiw** [comment]
Thanks for your interest in our work. I am currently a bit capacity-constrained and will look into cleaning up the pre-training code later. The processed pre-training data is a bit too large. I will need to think about how to do that.

**Comment by liruiw** [comment]
This might not directly related. But the released code here has some training-related information.https://github.com/liruiw/HMA
