### ISSUE TITLE
the dimensions of the action

### ISSUE THREAD

**Issue by 2814894078** [liruiw/HPT#21]
Can I understand it like this: In real-world deployment, instead of a simulated environment, for a self-created dataset, the dimensions of the action should include [x, y, z, roll, pitch, yaw] rather than [joint_1_angle, joint_2_angle, ..., joint_6_angle], and it should not include the gripper. The dimensions of the state can be defined according to our own requirements.

**Comment by liruiw** [comment]
Right. It also can be joint angles or including grippers, as the pre-training datasets have those examples.
