### ISSUE TITLE
Positional Encoding in Cross Attention

### ISSUE THREAD

**Issue by BaldPulse** [liruiw/HPT#22]
Why is positional encoding added before feature computation?
in [hpt/models/policy.py](https://github.com/liruiw/HPT/blob/ddf8f668deb9bb5364abf2733e630b6a32c49598/hpt/models/policy.py#L266-L271)  positional encodings are added
```python
positional_embedding = get_sinusoid_encoding_table(
    0, horizon * int(np.prod(data_shape[2:-1])), data_shape[-1]
).to(data[modality])
positional_embedding = einops.repeat(positional_embedding, "b h w -> (repeat b) h w", repeat=data_shape[0])
data[modality] = data[modality] + positional_embedding.view(data[modality].shape)
stem_token = stem.compute_latent(data[modality])
```
but [here](https://github.com/liruiw/HPT/blob/ddf8f668deb9bb5364abf2733e630b6a32c49598/hpt/models/policy_stem.py#L82-L87) features are computed afterwards
```python
def compute_latent(self, x: torch.Tensor) -> torch.Tensor:
...
  stem_feat = self(x)  
  stem_feat = stem_feat.reshape(stem_feat.shape[0], -1, stem_feat.shape[-1])  # (32, 147, 128)
  # Replicating tokens for each item in the batch and computing cross-attention
  stem_tokens = self.tokens.repeat(len(stem_feat), 1, 1)  # (32, 16, 128)
  stem_tokens = self.cross_attention(stem_tokens, stem_feat)  # (32, 16, 128)
  return stem_tokens
```
Is this a bug?

**Comment by liruiw** [comment]
Thanks for the questions. If I understand correctly, the question is on why position encoding is needed before the cross attention. The main reason is that there are temporal and spatial information potentially contained in the proprioception and vision features, so it needs to disambiguate before the cross attention.

**Comment by motor-x** [comment]
May I ask, why do you prefer to sinusoid positional embedding rather than learnable positional embedding (usually used for state and action tokens)?

**Comment by BaldPulse** [comment]
> Thanks for the questions. If I understand correctly, the question is on why position encoding is needed before the cross attention. The main reason is that there are temporal and spatial information potentially contained in the proprioception and vision features, so it needs to disambiguate before the cross attention.

Thanks for the reply. However, I think you misunderstood my question. I'm asking why positional encoding is added before embedding computation. For instance, if the obs is an image, the order should be 
1. the image is tokenized into embeddings by resnet
2. positional encodings are added to the embeddings
3. apply cross attention. 
However, in the code snippets **positional encodings are added before passing the image through resnet**. 

I am wondering whether this is intentional or a bug? If it is a bug, was the code used in pre-training correct?

**Comment by liruiw** [comment]
> May I ask, why do you prefer to sinusoid positional embedding rather than learnable positional embedding (usually used for state and action tokens)?
There is no particular reason. Feel free to ablate the other one.

**Comment by liruiw** [comment]
>I am wondering whether this is intentional or a bug? If it is a bug, was the code used in pre-training correct?


This code is not used in pre-training. I understand your question now. The Resnet stems are actually also not used in finetuning code. The code almost always uses pre-processed features. This can be an issue that I introduce in clean up.

**Comment by BaldPulse** [comment]
> > I am wondering whether this is intentional or a bug? If it is a bug, was the code used in pre-training correct?
> 
> This code is not used in pre-training. I understand your question now. The Resnet stems are actually also not used in finetuning code. The code almost always uses pre-processed features.
> 
> In other words, this can be an issue that I introduce in clean up. But the resnet stem is not needed. ResNet should be put in the encoder rather than the stem. I will need to take a look at this later.

I see. Thank you!
