### ISSUE TITLE
action horizon difference

### ISSUE THREAD

**Issue by yotofu** [liruiw/HPT#23]
![image](https://github.com/user-attachments/assets/fbe3c4c0-19ad-4229-bb6a-27f2eafc2bd2)
![image](https://github.com/user-attachments/assets/cb202e5f-01f2-4e6c-8355-789014e9c571)
Great job and need help~
I confused that there are two action horizons, one is in  network, another is in diffusion policy head, if i use diffusion policy head, what value i should set in network, same as action horizon in diffusion policy head?

**Comment by liruiw** [comment]
The action horizon in the network refers to the open-loop. execution in rollout.

**Comment by yotofu** [comment]
I found only "token_postprocessing" set  be action token, the action horizon in network will be available, Did you try set action horizon greater than 1 and use diffusion policy head? I got this error 
![image](https://github.com/user-attachments/assets/608424eb-7574-43d3-9bcb-bf101f1686e7)

**Comment by liruiw** [comment]
action_horizon should be used in the inference code. Basically for all steps modulo action_horizon is not 0, the network does not compute forward pass and just reuse previous action predictions. 

For the error, is that training time or test time? I might not have tested the diffusion head thoroughly. But also, "token_postprocessing" = action token and diffusion heads should not use together.
