### ISSUE TITLE
Use HPT policy for real UR robot

### ISSUE THREAD

**Issue by Nadish-Madadi** [liruiw/HPT#24]
I'm new to robot learning and was wondering how the HPT policy could be used for a real robot. I have a 6dof UR10e robot that I would like evaluate on, to perform manipulation tasks. I would like to receive a pose array of either 6 joint angles or [x,y,z,yaw,pitch,roll] and a gripper command. I went through the quickstart.ipynb, what are each of the values in the action output, I see 4 values? What do the observation values in the array indicate? For the observation can I pass in an array of joint angles?

**Comment by liruiw** [comment]
In practice, you will need to finetune the pre-trained model with the 6-dof UR robot that you have. In other words, 
 the observation and action spaces are user-defined.

**Comment by Nadish-Madadi** [comment]
> In practice, you will need to finetune the pre-trained model with the 6-dof UR robot that you have. In other words, the observation and action spaces are user-defined.

Is there any fine tuning code provided? Also is it possible to fine-tune on the Berkeley UR5 Autolab dataset?

**Comment by liruiw** [comment]
Yes. The finetuning README is here https://github.com/liruiw/HPT?tab=readme-ov-file#-try-this-on-your-own-dataset
