### ISSUE TITLE
How to visualize Metaworld simulation results?

### ISSUE THREAD

**Issue by SDKBig** [liruiw/HPT#25]
Great job and need help~     I wanna to know how to view Metaworld simulation results and specify the corresponding weight model for running in Metaworld?

**Comment by liruiw** [comment]
The metaworld results can be saved locally to videos, or can be exported to wandb for viewing.

**Comment by SDKBig** [comment]
> The metaworld results can be saved locally to videos, or can be exported to wandb for viewing.

Could you be more specific and provide an example of how to set it up?

**Comment by liruiw** [comment]
[This](https://github.com/liruiw/HPT/blob/main/env/mujoco/metaworld/rollout_runner.py#L186) can be a starting point to save and visualize the videos
