### ISSUE TITLE
Shared or Separated Proprioceptive Tokenizer?

### ISSUE THREAD

**Issue by motor-x** [liruiw/HPT#26]
Hi,

When using different datasets for training, do you have a shared Proprioceptive Tokenizer over all robots or Separated one for each robot?

Thanks!

**Comment by motor-x** [comment]
I guess we can have separate MLP for different embodiment but having a shared CrossAttention piece over embodiments, right?

**Comment by liruiw** [comment]
Good point. We use separate ones for each robot but It's not necessary to separate cross-attention pieces indeed.
