### ISSUE TITLE
Will other simulator benchmark evaluation code be released?

### ISSUE THREAD

**Issue by Fisher-Wang** [liruiw/HPT#3]
Thanks for your amazing work for providing invaluable insights on cross-embodiment pretraining for robot manipulation. I noticed the paper says HPT is evaluated on several simulation benchmarks, including MetaWorld, RoboMimic, Fleet-Tools and Simpler. And MetaWorld is included in this repo. Could you open-source the other benchmarks' evaluation code? Especially, I'm very interested in Simpler, because its real2sim feature.

**Comment by liruiw** [comment]
You can find some of the Simpler Env Code with proprioception inputs in this PR https://github.com/simpler-env/SimplerEnv/pull/3. I might need more time to look into releasing the evaluation code from other benchmarks. Thanks for understanding.
