### ISSUE TITLE
mujoco module issues

### ISSUE THREAD

**Issue by z111222333** [liruiw/HPT#5]
"Is this module using an older version? After following the author's suggestion to download and install this version, it keeps giving errors."
wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz  -O mujoco210.tar.gz --no-check-certificate
tar -xvzf mujoco210.tar.gz
AttributeError: module 'env.mujoco' has no attribute 'metaworld'
ImportError: Error loading 'env.mujoco.metaworld.rollout_runner.generate_dataset_rollouts'

**Comment by linxia676** [comment]
我也是这样的，我还以为是我环境没有配对，目前有什么办法解决吗

**Comment by liruiw** [comment]
Thanks for the questions. I think this has to do with the library path in the run time, as this file certainly exists and I can run it without problems.

**Comment by artyom-05-05** [comment]
```sudo apt install patchelf```
This command worked for me

**Comment by sidhu820** [comment]
> "Is this module using an older version? After following the author's suggestion to download and install this version, it keeps giving errors." wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco210.tar.gz --no-check-certificate tar -xvzf mujoco210.tar.gz AttributeError: module 'env.mujoco' has no attribute 'metaworld' ImportError: Error loading 'env.mujoco.metaworld.rollout_runner.generate_dataset_rollouts'

Hello there, did you got the solution for the problem? am also encountering the same?

**Comment by liruiw** [comment]
Maybe try this? https://github.com/liruiw/HPT/issues/5#issuecomment-2456589434

**Comment by sidhu820** [comment]
> Maybe try this? [#5 (comment)](https://github.com/liruiw/HPT/issues/5#issuecomment-2456589434)

My issue is solved when i try after reinstall the mujoco-py

**Comment by Nadish-Madadi** [comment]
I was able to fix the issue with these commands:

`sudo apt-get install libglew-dev`
`pip install sentencepiece`

**Comment by SMrLiang** [comment]
> `sudo apt install patchelf` This command worked for me

how about pip install patchelf
